BarPass/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('core.urls')),
]

core/urls.py
from django.conf.urls import patterns, include, url
from .views import *
from django.contrib.auth.decorators import login_required

urlpatterns = patterns('',
  url(r'^$', Home.as_view(), name='home'),
  url(r'^user/', include('registration.backends.simple.urls')),
  url(r'^user/', include('django.contrib.auth.urls')),
  url(r'^review/create/$', login_required(ReviewCreateView.as_view()), name='review_create'),
  url(r'review/$', login_required(ReviewListView.as_view()), name='review_list'),
  url(r'^review/(?P<pk>\d+)/$', login_required(ReviewDetailView.as_view()), name='review_detail'),
  url(r'^review/update/(?P<pk>\d+)/$', login_required(ReviewUpdateView.as_view()), name='review_update'),
  url(r'^review/delete/(?P<pk>\d+)/$', login_required(ReviewDeleteView.as_view()), name='review_delete'),
  url(r'^review/(?P<pk>\d+)/comment/create/$', login_required(CommentCreateView.as_view()), name='comment_create'),
  url(r'^review/(?P<review_pk>\d+)/comment/update/(?P<comment_pk>\d+)/$', login_required(CommentUpdateView.as_view()), name='comment_update'),
  url(r'^review/(?P<review_pk>\d+)/comment/delete/(?P<comment_pk>\d+)/$', login_required(CommentDeleteView.as_view()), name='comment_delete'),
  url(r'^vote/$', login_required(VoteFormView.as_view()), name='vote'),
  url(r'^user/(?P<slug>\w+)/$', login_required(UserDetailView.as_view()), name='user_detail'),
  url(r'^user/update/(?P<slug>\w+)/$', login_required(UserUpdateView.as_view()), name='user_update'),
  url(r'^user/delete/(?P<slug>\w+)/$', login_required(UserDeleteView.as_view()), name='user_delete'),
  url(r'^search/$', login_required(SearchReviewListView.as_view()), name='search'),
)

core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
VISIBILITY_CHOICES = (
(0, 'Public'),
(1, 'Anonymous'),
)

# Create your models here.
class Review(models.Model):
  title = models.CharField(max_length=300)
  description = models.TextField(null=True, blank=True)
  created_at = models.DateTimeField(auto_now_add=True)
  user = models.ForeignKey(User)
  visibility = models.IntegerField(choices=VISIBILITY_CHOICES, default=0)

  def __unicode__(self):
    return self.title

  def get_absolute_url(self):
    return reverse("review_detail", args=[self.id])

class Comment(models.Model):
  review = models.ForeignKey(Review)
  user = models.ForeignKey(User)
  created_at = models.DateTimeField(auto_now_add=True)
  text = models.TextField()
  visibility = models.IntegerField(choices=VISIBILITY_CHOICES, default=0)

  def __unicode__(self):
    return self.text

class Vote(models.Model):
    user = models.ForeignKey(User)
    review = models.ForeignKey(Review, blank=True, null=True)
    comment = models.ForeignKey(Comment, blank=True, null=True)

    def __unicode__(self):
        return "%s upvoted" % (self.user.username)

templates/review/review_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<p class="lead">Are you sure you want to delete "{{ review.title }}"</p>
<form method="post" action="">
  {% csrf_token %}
  <button type="submit" class="btn btn-primary">Delete</button>
</form>
{% endblock %}

templates/review/review_detail.html
{% extends 'base.html' %}
{% block content %}
<h1>{{ review.title }}</h1>
<p>{{ review.description }}</p>
<p>Asked {% if review.visibility == 0 %} by <a href="{% url 'user_detail' slug=review.user.username %}">{{ review.user.username }}</a> {% endif %} on {{ review.created_at }}</p>
{% if review.user == user %}
<p><a href="{% url 'review_update' pk=review.id %}">Edit review</a></p>
<p><a href="{% url 'review_delete' pk=review.id %}">Delete review</a></p>
{% endif %}
{% if comments.count > 0 %}
<h3>{{ comments.count }} Comment{{ comments.count|pluralize }}:</h3>
{% endif %}
{% for comment in comments %}
<div class="panel">
  <p>{{ comment.text }}</p>
  {% if comment.user == user %}
  <p><a href="{% url 'comment_update' review_pk=review.id comment_pk=comment.id %}">Edit comment</a></p>
  <p><a href="{% url 'comment_delete' review_pk=review.id comment_pk=comment.id %}">Delete comment</a></p>
  {% endif %}
  <p>Commented {% if comment.visibility == 0 %} by <a href="{% url 'user_detail' slug=comment.user.username %}">{{ comment.user.username }}</a> {% endif %} on {{ comment.created_at }}</p>
  <form method="post" action="{% url 'vote' %}">
    <span class="badge">{{ comment.vote_set.all.count }} Vote{{  comment.vote_set.all.count|pluralize }}</span>
    {% csrf_token %}
    <input type="hidden" name="comment" value="{{ comment.id }}" />
    <input type="hidden" name="review" value="{{ review.id }}" />
    <input type="hidden" name="user" value="{{ user.id }}" />
    {% if comment in user_votes %}
    <button class="btn btn-link">
      <span class="glyphicon glyphicon-thumbs-down"></span>
    </button>
    {% else %}
    <button class="btn btn-link">
      <span class="glyphicon glyphicon-thumbs-up"></span>
    </button>
    {% endif %}
  </form>
</div>
{% endfor %}
{% if not user_comments %}
<p><a href="{% url 'comment_create' pk=review.id %}">Write</a></p>
{% endif %}
{% endblock %}

templates/review/review_form.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block content %}
<div class="row">
  <div class="col-lg-6">
    <form method="post" action="">
      {% csrf_token %}
      {% bootstrap_form form %}
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
  </div>
</div>
{% endblock %}

templates/review/review_list.html
{% extends 'base.html' %}
{% block content %}
{% for review in object_list %}
<div class="panel">
  <h3><a href="{{ review.get_absolute_url }}">{{ review.title }}</a></h3>
  <p>Asked {% if review.visibility == 0 %} by <a href="{% url 'user_detail' slug=review.user.username %}">{{ review.user.username }}</a> {% endif %} on {{ review.created_at }}</p>
  <form method="post" action="{% url 'vote' %}">
    <span class="badge">{{ review.comment_set.all.count }} Comment{{  review.comment_set.all.count|pluralize }}</span>
    <span class="badge">{{ review.vote_set.all.count }} Vote{{ review.vote_set.all.count|pluralize }}</span>
    {% csrf_token %}
    <input type="hidden" name="review" value="{{ review.id }}" />
    <input type="hidden" name="user" value="{{ user.id }}" />
    {% if review in user_votes %}
    <button class="btn btn-link">
      <span class="glyphicon glyphicon-thumbs-down"></span>
    </button>
    {% else %}
    <button class="btn btn-link">
      <span class="glyphicon glyphicon-thumbs-up"></span>
    </button>
    {% endif %}
  </form>
</div>
{% empty %}
<p>No results found.</p>
{% endfor %}
{% if is_paginated %}
<nav>
  <ul class="pager">
    {% if page_obj.has_previous %}
    <li><a href="?page={{ page.obj.previous_page_number }}">Previous</a></li>
    {% endif %}
    {% if page_obj.has_next %}
    <li><a href="?page={{ page_obj.next_page_number }}">Next</a></li>
    {% endif %}
  </ul>
</nav>
{% endif %}
{% endblock %}